// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package common

import (
	"time"
)

const TableNameExample = "examples"

// Example mapped from table <examples>
type Example struct {
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	CreateUserID string    `gorm:"column:create_user_id;not null" json:"create_user_id"`
	UpdateUserID string    `gorm:"column:update_user_id;not null" json:"update_user_id"`
	TenantID     string    `gorm:"column:tenant_id;not null" json:"tenant_id"`
	ID           string    `gorm:"column:id;primaryKey" json:"id"`
	Name         string    `gorm:"column:name;not null" json:"name"`
	Email        string    `gorm:"column:email;not null" json:"email"`
	IsDeleted    bool      `gorm:"column:is_deleted" json:"is_deleted"`
}

// TableName Example's table name
func (*Example) TableName() string {
	return TableNameExample
}
