# 開発とテストのための2つの独立したMySQLコンテナを作成します。
# https://qiita.com/ucan-lab/items/b094dbfc12ac1cbee8cb
version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: "local-db"
    env_file:
      - ./.env
    ports:
      - "$POSTGRES_PORT:5432"
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d
  web:
    container_name: web
    build: . # イメージのビルドに使用するDockerfileへの相対パス
    volumes:
      # バインドマウント
      - type: bind
        source: . # ホスト側のディレクトリ
        target: /app # コンテナ側のディレクトリ
    env_file:
      - ./.env
    ports:
      - 5050:5050
    # 依存するサービス名(先に起動させたいサービス)
    depends_on:
      - db
volumes:
  database:
    driver: local
