// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package tenant

const TableNameAttachmentFile = "attachment_files"

// AttachmentFile mapped from table <attachment_files>
type AttachmentFile struct {
	CreateUserID string `gorm:"column:create_user_id;not null" json:"create_user_id"`
	UpdateUserID string `gorm:"column:update_user_id;not null" json:"update_user_id"`
	TenantID     string `gorm:"column:tenant_id;not null" json:"tenant_id"`
	ID           string `gorm:"column:id;primaryKey" json:"id"`
	Name         string `gorm:"column:name;not null" json:"name"`
	Size         int64  `gorm:"column:size;not null" json:"size"`
	ContentType  string `gorm:"column:content_type;not null" json:"content_type"`
	IsDeleted    bool   `gorm:"column:is_deleted" json:"is_deleted"`
	TodoID       string `gorm:"column:todo_id;not null" json:"todo_id"`
}

// TableName AttachmentFile's table name
func (*AttachmentFile) TableName() string {
	return TableNameAttachmentFile
}
