// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package tenant

const TableNameMigration = "migrations"

// Migration mapped from table <migrations>
type Migration struct {
	ID string `gorm:"column:id;primaryKey" json:"id"`
}

// TableName Migration's table name
func (*Migration) TableName() string {
	return TableNameMigration
}
